### PR TITLE
fix: type error

### LINKED ISSUE #476: [BUG] config types missing
**Describe the bug**
Since #449, the type of the plugin is `ESLint.Plugin`, which doesn't include the types of the configs.

**To Reproduce**
- Add html-eslint to a typescript config, using an exported config. (I tried to write a repro but couldn't find a nice playground/sandbox). LMK if you just want a repo.

**Expected behavior**
The type of `Plugin.configs` should be `{"flat/recommended": Linter.Config, "flat/all": Linter.Config }`, where right now it's `Record<string, LegacyConfigObject<RulesConfig, RulesConfig> | ConfigObject<RulesConfig> | ConfigObject<RulesConfig>[]> | undefined`

**Additional context**

### PR DESCRIPTION
**Pull request by yeonjuan**
## Checklist

- Addresses an existing open issue: fixes #476

### CODE REVIEW

File: packages/eslint-plugin/lib/index.js [hunk 1]
```diff
@@ -9,7 +9,6 @@ const { name, version } = require("../package.json");
 const parser = require("@html-eslint/parser");
 /** @import {ESLint} from "eslint" */
```
Comment (lishaduck) [inline packages/eslint-plugin/lib/index.js:11]: What I'd originally written:

```suggestion

/** @satisfies {ESLint.Plugin} */
```

The issue being that breaking changes to `ESLint.Plugin` (why you set it to `@type` in #449) don't get ignored, but my reading on #448 is that it'll be a non-issue once ESLint v10 gets released, so I'm not particularly concerned about it.
