### PR TITLE
fix: @html-eslint/indent rule breaks for Windows line endings

### LINKED ISSUE #85: @html-eslint/indent rule breaks for Windows line endings crlf
Running @html-eslint on Windows is not considering Windows line endings and failing therefore:

Config:
`'@html-eslint/indent': ['error', 2],`

File:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Test</title>
  </head>
  <body>
    <span>
      <i>some</i>
      thing
    </span>
  </body>
</html>
```

Error:
results in `8:19  error  Expected indentation of 6 space but found 5 space  @html-eslint/indent`

### PR DESCRIPTION
**Pull request by reinholdk**
fixes #85

Tries to detect CRLF and adjusts offsets when splitting text node lines.
Runs all ident test cases for LF and CRLF line breaks.

### CODE REVIEW

File: packages/parser/lib/postprocessor/postprocessor.js [hunk 1]
```diff
@@ -9,7 +9,8 @@ const {
 } = require("./utils");
 
 module.exports = class PostProcessor {
-  constructor() {
+  constructor(code) {
+    this.hasCRLF = code.indexOf("\r") !== -1;
```
Comment (yeonjuan) [inline packages/parser/lib/postprocessor/postprocessor.js]: @reinholdk Hi thanks for the fixing it. Your solutions seems works most cases. But it plus 1 for all text nodes when whole code has one `\r` even if the text node does not contain `\r`.

```
\r\n
<html>\n
   aaa\n
   aaa\n
</html>
```

I think the primary reason for this bug is [normalization newlines](https://infra.spec.whatwg.org/#normalize-newlines) process on tokenization. I think the processing not required for us .

so what do you think about removing the below lines instead of plus 1? 
https://github.com/yeonjuan/html-eslint/blob/main/packages/parser/lib/tokenizer/preprocessor.js#L111-L117

Comment (reinholdk) [reply packages/parser/lib/postprocessor/postprocessor.js]: @yeonjuan thanks for the hint. It seems to be working fine. Have reverted my initial change.

**Comment by yeonjuan** [comment]
@reinholdk Thanks! LGTM

**Comment by reinholdk** [comment]
@yeonjuan would it be possible to build a new release including this fix?
